'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class BatchBlockSummary
    Protected WithEvents Form1 As System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents Label1 As System.Web.UI.WebControls.Label
    Protected WithEvents lblNumberSamples As System.Web.UI.WebControls.Label
    Protected WithEvents chkByPassSort As System.Web.UI.WebControls.CheckBox
    Protected WithEvents grdBatchSummary As System.Web.UI.WebControls.DataGrid
    Protected WithEvents btnAddSubmission As System.Web.UI.WebControls.Button
    Protected WithEvents btnEditSubmission As System.Web.UI.WebControls.Button
    Protected WithEvents btnDeleteSubmission As System.Web.UI.WebControls.Button
    Protected WithEvents btnCopySubmission As System.Web.UI.WebControls.Button
    Protected WithEvents btnCancel As System.Web.UI.WebControls.Button
    Protected WithEvents ctlDiv As System.Web.UI.HtmlControls.HtmlGenericControl
    Protected WithEvents VLAFooter1 As VLAFooter
End Class
