'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Batch class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class Batch

    '''<summary>
    '''lblContactName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpecies As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmissionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmissionDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmittedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmittedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmittedArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmittedArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEnteredBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEnteredArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEnteredByVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredByVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmittedByVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmittedByVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectCodeVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectCodeVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblContactNameVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactNameVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpeciesVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpeciesVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEnteredAreaVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEnteredAreaVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmittedAreaVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmittedAreaVal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmissionDateVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmissionDateVal As Global.System.Web.UI.WebControls.Label
End Class
