'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''EditQCNote class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class EditQCNote

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ctlDivChooseQCNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDivChooseQCNote As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblChooseQCNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChooseQCNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlQCNotes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQCNotes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblQCNoteRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQCNoteRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQCNoteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQCNoteLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmissionNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmissionNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSubmissionNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubmissionNumberLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProjectLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpeciesLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpeciesLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStainRefLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStainRefLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSpecies control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpecies As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStainRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStainRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCreatedBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDateCreated control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateCreated As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQCNoteText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQCNoteText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valQCNoteText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valQCNoteText As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''btnDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDone As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ctlDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''VLAFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAFooter1 As Global.HistopathologySystem.VLAFooter
End Class
