'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''SearchArchiveLocation class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class SearchArchiveLocation

    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''lblHistRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHistRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtHistRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHistRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSenderRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSenderRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlArchiveLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlArchiveLocation As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rbTissues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbTissues As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''ddlTissue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTissue As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rbBlock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbBlock As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''txtBlockRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBlockRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbSlide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSlide As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDone As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSenderRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSenderRef As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArchiveLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArchiveLocation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''revBlockArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revBlockArchive As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ctlDivGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDivGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbExpandAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExpandAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbCollapseAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCollapseAll As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ctlDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ctlDivBlockArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDivBlockArchive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdBlockArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdBlockArchive As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''ctlDivTissueArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDivTissueArchive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdTissueArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdTissueArchive As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''ctlDivSlideArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ctlDivSlideArchive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''grdSlideArchive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdSlideArchive As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''hlExcelExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlExcelExport As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''VLAFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VLAFooter1 As Global.HistopathologySystem.VLAFooter
End Class
