'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''HistologyRef class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class HistologyRef

    '''<summary>
    '''txtHistologyRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHistologyRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvHistologyRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvHistologyRef As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''valHistologyRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valHistologyRef As Global.System.Web.UI.WebControls.CustomValidator
End Class
